# Feature Engineering

In [145]:
import pandas
def Prepro(df_train):
    return df_train
def encoding(df_train):
    X = []
    if 'target_1' in df_train.columns:
        Y1 = df_train['target_1'].values
        Y2 = df_train['target_2'].values
        del df_train['target_2']
        del df_train['target_1']
        del df_train['cm_key']
        df_tr = df_train[df_train.columns[:43]]
        X = df_tr.to_dict('records')
        from sklearn.feature_extraction import DictVectorizer
        enc = DictVectorizer()
        Xenc =enc.fit_transform(X)
        return [Xenc,Y1,Y2]
    else:
        del df_train['cm_key']
        df_tr = df_train[df_train.columns[:43]]
        X = df_tr.to_dict('records')
        from sklearn.feature_extraction import DictVectorizer
        enc = DictVectorizer()
        Xenc =enc.fit_transform(X)
        return [Xenc]

def encoding2(df_train):
    X = []
    if 'target_1' in df_train.columns:
        Y1 = df_train['target_1'].values
        Y2 = df_train['target_2'].values
        del df_train['target_2']
        del df_train['target_1']
        del df_train['cm_key']
        df_tr = df_train[df_train.columns[:43]]
        X = df_tr.to_dict('records')
        from sklearn.feature_extraction import DictVectorizer
        enc = DictVectorizer()
        Xenc =enc.fit_transform(X)
        return [Xenc,Y1,Y2]
    else:
        df_tr = df_train[df_train.columns[:43]]
        X = df_tr.to_dict('records')
        from sklearn.feature_extraction import DictVectorizer
        enc = DictVectorizer()
        Xenc =enc.fit_transform(X)
        return [Xenc]   
def prepros2(df_train):
    df_train['ElecSt'] =  df_train['mvar16']+df_train['mvar17']+df_train['mvar18']+df_train['mvar19']
    K  = df_train['ElecSt'].values>0
    df_train['ElecB']  = K*1
    for i in [u'mvar16', u'mvar17', u'mvar18',u'mvar19']:
        df_train[i+'R'] = df_train[i]/df_train['ElecSt']
    df_train['TravelSt'] =  df_train['mvar20']+df_train['mvar21']+df_train['mvar22']+df_train['mvar23']
    K  = df_train['TravelSt'].values>0
    df_train['TravelB']  = K*1
    for i in [u'mvar20', u'mvar21', u'mvar22',u'mvar23']:
        df_train[i] = df_train[i]/df_train['TravelSt']
        
    df_train['HouseSt'] =  df_train['mvar24']+df_train['mvar25']+df_train['mvar26']+df_train['mvar27']
    K  = df_train['HouseSt'].values>0
    df_train['HouseB']  = K*1
    for i in [u'mvar24', u'mvar25', u'mvar26',u'mvar27']:
        df_train[i] = df_train[i]/df_train['HouseSt']
    
    
    df_train['CarSt'] =  df_train['mvar28']+df_train['mvar29']+df_train['mvar30']+df_train['mvar31']
    K  = df_train['CarSt'].values>0
    df_train['CarB']  = K*1

    for i in [u'mvar28', u'mvar29', u'mvar30',u'mvar31']:
        df_train[i] = df_train[i]/df_train['CarSt']

    df_train['RetSt'] =  df_train['mvar32']+df_train['mvar33']+df_train['mvar34']+df_train['mvar35']
    K  = df_train['RetSt'].values>0
    df_train['RetB']  = K*1
    for i in [u'mvar32', u'mvar33', u'mvar34',u'mvar35']:
        df_train[i] = df_train[i]/df_train['RetSt']
    df_train['TLC'] = df_train['mvar40']+df_train['mvar41']+df_train['mvar42']+df_train['mvar43']+df_train['mvar44']+df_train['mvar45']
    df_train['TLCcard'] = df_train['mvar43']+ df_train['mvar44']+df_train['mvar45']
    df_train['TLCoffer'] =df_train['mvar40']+ df_train['mvar41']+df_train['mvar42']
    for i in ['TLC','TLCcard','TLCoffer']:
        K  = df_train[i].values>0
        df_train[i+'B']  = K*1 
    
    K  = df_train['mvar3'].values>0 ############
    df_train['mvar3B']  = K*1
    
    K  = df_train['mvar4'].values>4.5 ##########
    df_train['mvar4B']  = K*1

    K  = df_train['mvar5'].values>0
    df_train['mvar5B']  = K*1

    K  = df_train['mvar6'].values>1000
    df_train['mvar6B']  = K*1
    
    K  = df_train['mvar7'].values>0
    df_train['mvar7B']  = K*1

    K  = df_train['mvar8'].values>0
    df_train['mvar8B']  = K*1

    K  = df_train['mvar9'].values>0
    df_train['mvar9B']  = K*1
    
    K  = df_train['mvar15'].values>0
    df_train['mvar15B']  = K*1
    
    df_train['B']  = df_train['mvar3B']+df_train['mvar4B'] +df_train['mvar5B']+df_train['mvar6B'] +df_train['mvar7B']
    
    df_train['TS'] = df_train['mvar36']+df_train['mvar37']+df_train['mvar38']+df_train['mvar39']
    for i in [u'mvar36', u'mvar37', u'mvar38',u'mvar39']:
        df_train[i] = df_train[i]/df_train['TS']
    for i in [0,1,2,3]:
         df_train['q'+str(1+i)] = df_train['mvar'+str(16+i)]+ df_train['mvar'+str(20+i)] + df_train['mvar'+str(24+i)] + df_train['mvar'+str(28+i)] + df_train['mvar'+str(32+i)] +df_train['mvar'+str(36+i)]

    K  = df_train['mvar2'].values<6
    df_train['smallF']  = K*1   
    K  = df_train['mvar2'].values >=6
    df_train['longF']  = K*1   
    df_train  = df_train.fillna(0)
    
    df_train['A']  = df_train['mvar3'] - df_train['TS']
    df_train['B']  = df_train['mvar7']*df_train['TS']
    return df_train
def encoding(df_train):
    X = []
    if 'target_1' in df_train.columns:
        Y1 = df_train['target_1'].values
        Y2 = df_train['target_2'].values
        del df_train['target_2']
        del df_train['target_1']
        del df_train['cm_key']
        df_tr = df_train[df_train.columns[:43]]
        X = df_tr.to_dict('records')
        from sklearn.feature_extraction import DictVectorizer
        enc = DictVectorizer()
        Xenc =enc.fit_transform(X)
        return [Xenc,Y1,Y2]
    else:
        del df_train['cm_key']
        df_tr = df_train[df_train.columns[:43]]
        X = df_tr.to_dict('records')
        from sklearn.feature_extraction import DictVectorizer
        enc = DictVectorizer()
        Xenc =enc.fit_transform(X)
        return [Xenc]

def encoding2(df_train):
    X = []
    if 'target_1' in df_train.columns:
        Y1 = df_train['target_1'].values
        Y2 = df_train['target_2'].values
        del df_train['target_2']
        del df_train['target_1']
        del df_train['cm_key']
        df_tr = df_train[df_train.columns[:43]]
        X = df_tr.to_dict('records')
        from sklearn.feature_extraction import DictVectorizer
        enc = DictVectorizer()
        Xenc =enc.fit_transform(X)
        return [Xenc,Y1,Y2]
    else:
        df_tr = df_train[df_train.columns[:43]]
        X = df_tr.to_dict('records')
        from sklearn.feature_extraction import DictVectorizer
        enc = DictVectorizer()
        Xenc =enc.fit_transform(X)
        return [Xenc]   
def prepros2(df_train):
    for i in [0,1,2,3]:
         df_train['q'+str(1+i)] = df_train['mvar'+str(16+i)]+ df_train['mvar'+str(20+i)] + df_train['mvar'+str(24+i)] + df_train['mvar'+str(28+i)] + df_train['mvar'+str(32+i)] +df_train['mvar'+str(36+i)]
    
    df_train['ElecSt'] =  df_train['mvar16']+df_train['mvar17']+df_train['mvar18']+df_train['mvar19']
    K  = df_train['ElecSt'].values>0
    df_train['ElecB']  = K*1
    for i in [u'mvar16', u'mvar20', u'mvar24',u'mvar28',u'mvar32']:
        df_train[i] = df_train[i]/df_train['q1']
    for i in [u'mvar17', u'mvar21', u'mvar25',u'mvar29',u'mvar33']:
        df_train[i] = df_train[i]/df_train['q2']
    for i in [u'mvar18', u'mvar22', u'mvar26',u'mvar30',u'mvar34']:
        df_train[i] = df_train[i]/df_train['q3']
    for i in [u'mvar19', u'mvar23', u'mvar27',u'mvar31',u'mvar35']:
        df_train[i] = df_train[i]/df_train['q4']
        
    df_train['TravelSt'] =  df_train['mvar20']+df_train['mvar21']+df_train['mvar22']+df_train['mvar23']
    K  = df_train['TravelSt'].values>0
    df_train['TravelB']  = K*1
        
    df_train['HouseSt'] =  df_train['mvar24']+df_train['mvar25']+df_train['mvar26']+df_train['mvar27']
    K  = df_train['HouseSt'].values>0
    df_train['HouseB']  = K*1

    
    
    df_train['CarSt'] =  df_train['mvar28']+df_train['mvar29']+df_train['mvar30']+df_train['mvar31']
    K  = df_train['CarSt'].values>0
    df_train['CarB']  = K*1


    df_train['RetSt'] =  df_train['mvar32']+df_train['mvar33']+df_train['mvar34']+df_train['mvar35']
    K  = df_train['RetSt'].values>0
    df_train['RetB']  = K*1

    
    df_train['TLC'] = df_train['mvar40']+df_train['mvar41']+df_train['mvar42']+df_train['mvar43']+df_train['mvar44']+df_train['mvar45']
    df_train['TLCcard'] = df_train['mvar43']+ df_train['mvar44']+df_train['mvar45']
    df_train['TLCoffer'] =df_train['mvar40']+ df_train['mvar41']+df_train['mvar42']
    for i in ['TLC','TLCcard','TLCoffer']:
        K  = df_train[i].values>0
        df_train[i+'B']  = K*1 
    
    K  = df_train['mvar3'].values>0 ############
    df_train['mvar3B']  = K*1
    
    K  = df_train['mvar4'].values>4.5 ##########
    df_train['mvar4B']  = K*1

    K  = df_train['mvar5'].values>0
    df_train['mvar5B']  = K*1

    K  = df_train['mvar6'].values>1000
    df_train['mvar6B']  = K*1
    
    K  = df_train['mvar7'].values>0
    df_train['mvar7B']  = K*1

    K  = df_train['mvar8'].values>0
    df_train['mvar8B']  = K*1

    K  = df_train['mvar9'].values>0
    df_train['mvar9B']  = K*1
    
    K  = df_train['mvar14'].values>0
    df_train['mvar14B']  = K*1
    
    df_train['B']  = df_train['mvar3B']+df_train['mvar4B'] +df_train['mvar5B']+df_train['mvar6B'] +df_train['mvar7B']
    
    df_train['TS'] = df_train['mvar36']+df_train['mvar37']+df_train['mvar38']+df_train['mvar39']
    for i in [u'mvar36', u'mvar37', u'mvar38',u'mvar39']:
        df_train[i] = df_train[i]/df_train['TS']

    K  = df_train['mvar2'].values<6
    df_train['smallF']  = K*1   
    K  = df_train['mvar2'].values >=6
    df_train['longF']  = K*1   
    df_train  = df_train.fillna(0)
    
    df_train['A']  = df_train['mvar3'] - df_train['TS']
    df_train['B']  = df_train['mvar7']*df_train['TS']
    df_train['C']  = df_train['mvar5']/12
    df_train['D']  = df_train['mvar7']/(df_train['mvar11']+0.0001)
    df_train['E']  = df_train['mvar4']/(df_train['mvar2']+1)
    
    return df_train




score = []
money = 0
def AMEXMETRIC(act,pred,score,money):
    for i in range(len(act)):
        if money < 6000:
            if act[i] == pred[i]:
                score.append(100)
                money  = money+6
            elif act[i] != pred[i] and act[i] !='None':
                score.append(100)
                money  = money+12
            elif act[i] =='None':
                score.append(0)
                money  = money+6
            j = i
    return sum(score),money,j
    
    return df_train




score = []
money = 0
def AMEXMETRIC(act,pred,score,money):
    for i in range(len(act)):
        if money < 6000:
            if act[i] == pred[i]:
                score.append(100)
                money  = money+6
            elif act[i] != pred[i] and act[i] !='None':
                score.append(100)
                money  = money+12
            elif act[i] =='None':
                score.append(0)
                money  = money+6
            j = i
    return sum(score),money,j

cols= [
 'cm_key',
 'mvar2',
 'mvar4',
 'mvar5',
 'mvar6',
 'mvar7',
 'mvar8',
 'mvar9',
 'mvar10',
 'mvar11',
 'mvar12',
 'mvar13',
 'mvar14',
 'mvar15',  
 'mvar16',
#  'mvar17',
#  'mvar18',
#  'mvar19',
#  'mvar20',
#  'mvar21',
#  'mvar22',
#  'mvar23',
#  'mvar24',
#  'mvar25',
#  'mvar26',
#  'mvar27',
#  'mvar28',
#  'mvar29',
#  'mvar30',
#  'mvar31',
#  'mvar32',
#  'mvar33',
#  'mvar34',
#  'mvar35',
 'mvar36',
 'mvar37',
 'mvar38',
 'mvar39',
 'mvar40',
 'mvar41',
 'mvar42',
 'mvar43',
 'mvar44',
 'mvar45',
 'ElecSt',
# 'ElecB',
 'TravelSt',
# 'TravelB',
 'HouseSt',
# 'HouseB',
 'CarSt',
# 'CarB',
 'RetSt',
# 'RetB',
 'TS',
 'longF',
 'smallF',
 'q1',
 'q2',
 'q3',
 'q4',
    'TLCB','TLCofferB','A','B','F'
]

def AMEXTRAIN(df_train,df_valid):
    df_train = prepros2(df_train)
    df_valid = prepros2(df_valid)
    Key1 = df_valid['cm_key'].values
    cols= [
     'cm_key',
     'mvar2',
     'mvar4',
     'mvar5',
     'mvar6',
     'mvar7',
     'mvar8',
     'mvar9',
     'mvar10',
     'mvar11',
     'mvar12',
     'mvar13',
     'mvar14',
     'mvar15',  
     'mvar16',
    #  'mvar17',
    #  'mvar18',
    #  'mvar19',
    #  'mvar20',
    #  'mvar21',
    #  'mvar22',
    #  'mvar23',
    #  'mvar24',
    #  'mvar25',
    #  'mvar26',
    #  'mvar27',
    #  'mvar28',
    #  'mvar29',
    #  'mvar30',
    #  'mvar31',
    #  'mvar32',
    #  'mvar33',
    #  'mvar34',
    #  'mvar35',
     'mvar36',
     'mvar37',
     'mvar38',
     'mvar39',
     'mvar40',
     'mvar41',
     'mvar42',
     'mvar43',
     'mvar44',
     'mvar45',
     'ElecSt',
    # 'ElecB',
     'TravelSt',
    # 'TravelB',
     'HouseSt',
    # 'HouseB',
     'CarSt',
    # 'CarB',
     'RetSt',
    # 'RetB',
     'TS',
     'longF',
     'smallF',
     'q1',
     'q2',
     'q3',
     'q4',
        'TLCB','TLCofferB','A','B','F'
    ]

    df_train = df_train[cols+[ 'target_1', 'target_2']]
    df_valid = df_valid[cols]
    #df_test = df_test[cols]

    df_train = Prepro(df_train)
    df_valid = Prepro(df_valid)
    train = encoding(df_train)
    valid = encoding(df_valid)
    X_tr = train[0]
    Y_tr_1  = train[1]
    Y_tr_2  = train[2]
    X_va = valid[0]


    # #Feature Union
    Y = Y_tr_2
    # pca = PCA(n_components=3)
    # selection = SelectKBest(k=25)
    # modelused = FeatureUnion([("pca", pca), ("univ_select", selection)])
    # X_TR = modelused.fit(X_tr.toarray(), Y).transform(X_tr.toarray())
    # X_VA = modelused.fit(X_tr.toarray(), Y).transform(X_va.toarray())

    X_TR = X_tr
    X_VA = X_va

    clf3 = GradientBoostingClassifier()#GradientBoostingClassifier(min_samples_leaf=200,max_depth=5,n_estimators=100)
    clf3.fit(X_TR,Y_tr_2)
    clf = GradientBoostingClassifier(learning_rate=0.01)#GradientBoostingClassifier(min_samples_leaf=200,max_depth=5,n_estimators=100)
    clf.fit(X_TR,Y_tr_1)
    return [df_train,df_valid, clf.predict_proba(X_VA.toarray()).T[0],clf3.predict_proba(X_VA.toarray()).T[2]]

In [146]:
probs1 = {}
probs2 = {}
for i in range(1):
    df_train = pandas.read_csv('ATRAIN.csv')#pandas.read_csv('AMTRAIN.csv')
    df_test = pandas.read_csv('AVALID.csv')
    del df_train['Unnamed: 0']
    del df_test['Unnamed: 0']
    df_valid = pandas.read_csv('Leaderboard.csv')#pandas.read_csv('AMVALID.csv')
    Key1 = df_valid['cm_key'].values
    df_train = pandas.concat([df_train,df_test])
    from sklearn.utils import shuffle
    df_train = shuffle(df_train)
    df_train = pandas.concat([df_train[df_train.target_1 == 0][:20000],df_train[df_train.target_1 == 1][:10000],df_train[df_train.target_1 == 1][:10000]])
    df_train = shuffle(df_train)
    AM = AMEXTRAIN(df_train,df_valid)
    probs1[i] = AM[2]
    probs2[i] = AM[3]
    df_train = AM[0] 
    df_valid = AM[1] 
    df_valid['proba'] = probs1[i]
    df_valid['proba2'] = probs2[i]
    df_valid['proba3'] = df_valid['proba']+3*df_valid['proba2']
    df_valid['KEY'] = Key1
    df_valid = df_valid.sort_values(['proba3'], ascending=True)
    df_valid2 = df_valid[:1000]
    df[i] = df_valid2

C:\Users\user\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel_launcher.py:188: RuntimeWarning: invalid value encountered in greater
C:\Users\user\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel_launcher.py:192: RuntimeWarning: invalid value encountered in greater
C:\Users\user\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel_launcher.py:198: RuntimeWarning: invalid value encountered in greater
C:\Users\user\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel_launcher.py:203: RuntimeWarning: invalid value encountered in greater

In [150]:
df_train = AM[0] 
df_valid = AM[1] 
df_valid['proba'] = AM[2]
df_valid['proba2'] = AM[3]
df_valid['proba3'] = df_valid['proba'] +3*df_valid['proba2']
df_valid['KEY'] = Key1
df_valid = df_valid.sort_values(['proba3'], ascending=True)
df_valid2 = df_valid[:1000]

In [151]:


df_train = pandas.read_csv('ATRAIN.csv')#pandas.read_csv('AMTRAIN.csv')
df_test = pandas.read_csv('AVALID.csv')
del df_train['Unnamed: 0']
del df_test['Unnamed: 0']
df_train = pandas.concat([df_train,df_test])

df_train = prepros2(df_train)
cols= [
 'cm_key',
 'mvar2',
 'mvar4',
 'mvar5',
 'mvar6',
 'mvar7',
 'mvar8',
 'mvar9',
 'mvar10',
 'mvar11',
 'mvar12',
 'mvar13',
 'mvar14',
 'mvar15',  
 'mvar16',
#  'mvar17',
#  'mvar18',
#  'mvar19',
#  'mvar20',
#  'mvar21',
#  'mvar22',
#  'mvar23',
#  'mvar24',
#  'mvar25',
#  'mvar26',
#  'mvar27',
#  'mvar28',
#  'mvar29',
#  'mvar30',
#  'mvar31',
#  'mvar32',
#  'mvar33',
#  'mvar34',
#  'mvar35',
 'mvar36',
 'mvar37',
 'mvar38',
 'mvar39',
 'mvar40',
 'mvar41',
 'mvar42',
 'mvar43',
 'mvar44',
 'mvar45',
 'ElecSt',
# 'ElecB',
 'TravelSt',
# 'TravelB',
 'HouseSt',
# 'HouseB',
 'CarSt',
# 'CarB',
 'RetSt',
# 'RetB',
 'TS',
 'longF',
 'smallF',
 'q1',
 'q2',
 'q3',
 'q4',
    'TLCB','TLCofferB','A','B','F'
]
df_train = df_train[cols+[ 'target_1', 'target_2']]

df_train = Prepro(df_train)


Key2 = df_valid2['KEY'].values
del df_valid2['KEY']
del df_valid2['proba']
del df_valid2['proba2']
del df_valid2['proba3']

df_train2 = df_train[df_train['target_1'] ==1]
Y_2  = df_train2['target_2'].values

del df_train2['target_1']
del df_train2['target_2']

del df_train2['mvar12']
del df_valid2['mvar12']

train = encoding2(df_train2)
valid = encoding2(df_valid2)
X_tr2 = train[0]
X_va2 = valid[0]

C:\Users\user\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel_launcher.py:188: RuntimeWarning: invalid value encountered in greater
C:\Users\user\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel_launcher.py:192: RuntimeWarning: invalid value encountered in greater
C:\Users\user\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel_launcher.py:198: RuntimeWarning: invalid value encountered in greater
C:\Users\user\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel_launcher.py:203: RuntimeWarning: invalid value encountered in greater

In [ ]:
clf2 = GradientBoostingClassifier(min_samples_leaf=100,learning_rate=0.01)
clf2.fit(X_tr2,Y_2)

In [152]:
df_valid2['KEY'] = Key2
df_valid2['pred'] = clf2.predict(X_va2.toarray())

# maxproba = []
# for i in clf.predict_proba(X_va2.toarray()):
#     maxproba.append(max(i))
# df_valid2['M']  = maxproba
# df_valid2 = df_valid2.sort_values(['M'], ascending=False)

df_valid = df_valid2[['KEY','pred']]
from sklearn.utils import shuffle
df_valid = shuffle(df_valid)
df_valid.to_csv('godlevelc4.csv',index=False,index_label=False,header=False)

C:\Users\user\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\user\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [153]:
df_valid

        KEY    pred
7945  57946    Supp
7425  57426   Elite
9804  59805    Supp
5168  55169    Supp
8376  58377    Supp
864   50865    Supp
3842  53843    Supp
6185  56186   Elite
9572  59573   Elite
9156  59157    Supp
818   50819   Elite
147   50148    Supp
7832  57833  Credit
2103  52104   Elite
3116  53117    Supp
1075  51076    Supp
6062  56063    Supp
586   50587    Supp
4914  54915  Credit
5981  55982    Supp
1272  51273    Supp
4655  54656    Supp
5870  55871   Elite
3449  53450    Supp
7537  57538    Supp
2254  52255    Supp
1065  51066    Supp
6497  56498    Supp
6818  56819  Credit
6206  56207    Supp
...     ...     ...
1103  51104  Credit
8151  58152  Credit
3532  53533    Supp
9239  59240    Supp
8716  58717    Supp
8698  58699  Credit
335   50336    Supp
5100  55101   Elite
5563  55564    Supp
3401  53402    Supp
6362  56363   Elite
4622  54623    Supp
4648  54649    Supp
2127  52128    Supp
4115  54116   Elite
1193  51194    Supp
5709  55710  Credit
4681  54682    Supp
4968  54969    Supp
5535  55536    Supp
9290  59291    Supp
241   50242    Supp
8500  58501    Supp
3164  53165    Supp
4094  54095    Supp
7257  57258    Supp
8772  58773    Supp
5929  55930   Elite
9022  59023    Supp
501   50502    Supp

[1000 rows x 2 columns]

In [ ]:
clf.predict(X_va2.toarray())[clf.predict_proba(X_va2.toarray()).T[2]>0.7]

In [243]:
df_valid['proba'] = sig_clf.predict_proba(X_VA.toarray()).T[1]
df_valid['KEY'] = Key1
df_valid = df_valid.sort_values(['proba'], ascending=False)
df_valid2 = df_valid[:1000]
Key2 = df_valid2['KEY'].values
del df_valid2['KEY']
del df_valid2['proba']

df_train['Tar'] = Y_tr_2
df_train['T'] = Y_tr_1
df_train2 = df_train[df_train['T'] ==1]
Y_2  = df_train2['Tar'].values

del df_train2['T']
del df_train2['Tar']
#ENCODING
X_train = df_train2.to_dict('records')
X_test = df_valid2.to_dict('records')
X_tr = []
X_te = []
X_tr.extend(X_train)
X_te.extend(X_test)
X_total = X_tr + X_te
#One Hot Encoding 
enc = DictVectorizer()
X_encoded_total =enc.fit_transform(X_total)
X_tr2 =X_encoded_total[:len(X_tr)]
X_va2 =X_encoded_total[len(X_tr):]

<1000x72 sparse matrix of type '<type 'numpy.float64'>'
	with 24576 stored elements in Compressed Sparse Row format>

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier,AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier,OneVsOneClassifier,OutputCodeClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn import svm
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest,chi2,SelectKBest,SelectFromModel
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.naive_bayes import MultinomialNB,BernoulliNB
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier,AdaBoostClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.multiclass import OneVsRestClassifier,OutputCodeClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
from collections import Counter
from sklearn.feature_extraction import DictVectorizer

In [271]:
def AMEX(df_train,df_valid,cols):
    Key1 = df_valid['cm_key'].values
    df_train = prepros2(df_train)
    df_valid = prepros2(df_valid)

    df_train = df_train[cols+[ 'target_1', 'target_2']]
    df_valid = df_valid[cols]
    #df_test = df_test[cols]

    df_train = Prepro(df_train)
    df_valid = Prepro(df_valid)
    train = encoding(df_train)
    valid = encoding(df_valid)
    X_tr = train[0]
    Y_tr_1  = train[1]
    Y_tr_2  = train[2]
    X_va = valid[0]


    # #Feature Union
    Y = Y_tr_2
    # pca = PCA(n_components=3)
    # selection = SelectKBest(k=25)
    # modelused = FeatureUnion([("pca", pca), ("univ_select", selection)])
    # X_TR = modelused.fit(X_tr.toarray(), Y).transform(X_tr.toarray())
    # X_VA = modelused.fit(X_tr.toarray(), Y).transform(X_va.toarray())

    X_TR = X_tr
    X_VA = X_va
    clf = GradientBoostingClassifier()
    clf.fit(X_tr,Y_tr_1)
    from sklearn.calibration import CalibratedClassifierCV

    sig_clf = CalibratedClassifierCV(clf, method="sigmoid", cv="prefit")
    sig_clf.fit(X_tr.toarray(), Y_tr_1)

    print confusion_matrix(Y_tr_1, sig_clf.predict(X_tr.toarray()))
    df_valid['proba'] = clf.predict_proba(X_VA.toarray()).T[1]
    df_valid['KEY'] = Key1
    df_valid = df_valid.sort_values(['proba'], ascending=False)
    df_valid2 = df_valid[:1000]
    Key2 = df_valid2['KEY'].values
    del df_valid2['KEY']
    del df_valid2['proba']

    df_train['Tar'] = Y_tr_2
    df_train['T'] = Y_tr_1
    df_train2 = df_train[df_train['T'] ==1]
    Y_2  = df_train2['Tar'].values

    del df_train2['T']
    del df_train2['Tar']

    del df_train2['mvar12']
    del df_valid2['mvar12']

    train = encoding2(df_train2)
    valid = encoding2(df_valid2)
    X_tr2 = train[0]
    X_va2 = valid[0]
    clf = GradientBoostingClassifier(min_samples_leaf=100)
    clf.fit(X_tr2,Y_2)
    df_valid2['KEY'] = Key2
    df_valid2['pred'] = clf.predict(X_va2.toarray())
    return df_valid2

    # maxproba = []
    # for i in clf.predict_proba(X_va2.toarray()):
    #     maxproba.append(max(i))
    # df_valid2['M']  = maxproba
    # df_valid2 = df_valid2.sort_values(['M'], ascending=False)
    #df_valid = df_valid2[['KEY','pred']]
    #df_valid.to_csv('kowshik_pred16.csv',index=False,index_label=False,header=False)

In [272]:
cols= [
 'cm_key',
 'mvar1',
 'mvar2',
 'mvar4',
 'mvar5',
 'mvar6',
 'mvar7',
 'mvar8',
 'mvar9',
 'mvar10',
 'mvar11',
 'mvar12',
 'mvar13',
 'mvar14',
 'mvar15',
 'mvar16',
 'mvar17',
 'mvar18',
 'mvar19',
 'mvar20',
 'mvar21',
 'mvar22',
 'mvar23',
 'mvar24',
 'mvar25',
 'mvar26',
 'mvar27',
 'mvar28',
 'mvar29',
 'mvar30',
 'mvar31',
 'mvar32',
 'mvar33',
 'mvar34',
 'mvar35',
 'mvar36',
 'mvar37',
 'mvar38',
 'mvar39',
 'mvar40',
 'mvar41',
 'mvar42',
 'mvar43',
 'mvar44',
 'mvar45',
 'ElecSt',
 'ElecB',
 'TravelSt',
 'TravelB',
 'HouseSt',
 'HouseB',
 'CarSt',
 'CarB',
 'RetSt',
 'RetB',
 'TS',
 'SingleF',
 'longF',
 'smallF']
import pandas
df_train = pandas.read_csv('AMTRAIN.csv')#pandas.read_csv('AMTRAIN.csv')
df_test = pandas.read_csv('AMVALID.csv')
del df_train['Unnamed: 0']
del df_test['Unnamed: 0']
df_train = pandas.concat([df_train,df_test])
df_valid = pandas.read_csv('Leaderboard_Dataset.csv')#pandas.read_csv('AMVALID.csv')
df = AMEX(df_train,df_valid,cols)

[[30498   624]
 [ 7976   902]]

C:\Users\user\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel_launcher.py:63: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\user\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel_launcher.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [273]:
df

,mvar1,mvar2,mvar4,mvar5,mvar6,mvar7,mvar8,mvar9,mvar10,mvar11,...,CarSt,CarB,RetSt,RetB,TS,SingleF,longF,smallF,KEY,pred
8930,Charge,0,1,5,0,0.2022,0.0000,2918974,0,0.7385,...,0.00,0,0.00,0,27094.79,1,0,0,58931,Elite
3236,Charge,3,2,5,0,0.1874,0.0000,2918974,0,1.8417,...,0.00,0,0.00,0,28030.66,0,0,1,53237,Elite
4,Charge,0,4,7,0,0.7969,0.2310,880618,0,2.6261,...,0.00,0,0.00,0,61838.76,1,0,0,50005,Elite
6403,Charge,1,3,11,0,0.1046,0.0000,2918974,0,0.8915,...,0.00,0,0.00,0,59762.92,1,0,0,56404,Elite
8681,Charge,0,4,9,0,0.0389,0.0000,2918974,0,1.0130,...,0.00,0,0.00,0,11914.84,1,0,0,58682,Elite
9688,Charge,0,1,8,0,0.1472,0.0000,2918974,0,2.6676,...,0.00,0,0.00,0,66918.72,1,0,0,59689,Elite
335,Charge,0,4,11,0,0.1015,0.0000,2918974,0,1.3574,...,0.00,0,0.00,0,32238.75,1,0,0,50336,Elite
7715,Charge,0,2,9,0,0.7969,0.3243,79563,0,1.8468,...,1826.12,1,40605.07,1,46274.63,1,0,0,57716,Credit
5918,Charge,0,4,11,0,0.7969,0.3466,768531,0,2.9866,...,0.00,0,0.00,0,143757.40,1,0,0,55919,Elite
6805,Charge,3,8,7,0,0.1904,0.0000,0,0,1.6431,...,191.75,1,28233.99,1,33029.91,0,0,1,56806,Elite
639,Charge,0,8,7,0,0.7969,0.1155,131614,0,2.4230,...,0.00,0,109277.88,1,87772.28,1,0,0,50640,Elite
2504,Charge,0,6,6,0,0.7969,0.6344,7255542,0,4.6905,...,0.00,0,0.00,0,65887.29,1,0,0,52505,Elite
3449,Charge,11,2,355,4830,6.1253,0.8831,34207020,1,6.3595,...,142602.82,1,5247160.06,1,2408202.79,0,1,0,53450,Supp
8850,Charge,0,1,9,0,0.7969,0.0000,2918974,0,3.0847,...,4545.48,1,72903.55,1,57844.03,1,0,0,58851,Elite
6714,Charge,0,2,6,0,0.7969,0.0000,2918974,0,1.3376,...,0.00,0,0.00,0,51076.62,1,0,0,56715,Elite
4132,Charge,0,0,7,0,0.3360,0.1155,118845,0,4.2382,...,0.00,0,0.00,0,82511.64,1,0,0,54133,Elite
7002,Charge,1,6,5,0,0.1905,0.0000,2918974,0,1.7237,...,39.96,1,42527.00,1,57690.34,1,0,0,57003,Elite
4701,Charge,11,12,119,4830,5.2314,0.0000,29315,1,7.0003,...,0.00,0,0.00,0,3257949.21,0,1,0,54702,Supp
4528,Charge,1,1,8,0,0.4361,0.0000,2918974,0,5.1709,...,0.00,0,0.00,0,94970.31,1,0,0,54529,Elite
4699,Charge,11,2,25,4830,7.8596,0.8831,34207020,1,6.4149,...,43.67,1,4955782.06,1,1912238.40,0,1,0,54700,Supp
4560,Charge,10,4,95,4054,2.9865,0.5926,3169200,1,6.4234,...,14333.96,1,1125016.74,1,1363625.64,0,1,0,54561,Supp
5802,Charge,5,1,7,0,0.7849,0.0000,2918974,0,5.0660,...,16585.07,1,151049.61,1,231224.01,0,1,0,55803,Supp
2523,Charge,0,4,8,0,0.0473,0.2682,66393,0,0.9937,...,0.00,0,0.00,0,7204.59,1,0,0,52524,Elite
8049,Charge,0,9,6,0,0.2608,0.1831,178509,0,6.4284,...,0.00,0,0.00,0,111245.12,1,0,0,58050,Elite
2559,Charge,9,3,21,272,0.6579,0.7303,13049130,0,6.1839,...,71257.85,1,223800.69,1,239735.91,0,1,0,52560,Supp
6080,Charge,10,4,144,4830,10.0000,0.6148,3314987,1,6.6252,...,1450.89,1,2113967.92,1,2024968.13,0,1,0,56081,Supp
15,Charge,1,7,7,0,0.4697,0.1831,169701,0,4.9309,...,4784.19,1,97848.55,1,126393.78,1,0,0,50016,Elite
8317,Charge,9,6,12,1105,0.9575,0.0000,2918974,0,6.4157,...,191781.90,1,443973.89,1,456651.01,0,1,0,58318,Supp
4914,Charge,11,6,140,2575,3.9871,0.5365,2696490,1,6.6345,...,27017.30,1,1886010.22,1,2044550.04,0,1,0,54915,Supp
8225,Charge,0,2,8,0,1.9858,0.0000,2918974,0,3.2843,...,35.87,1,116292.27,1,215270.42,1,0,0,58226,Elite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5897,Charge,0,4,69,601,0.7969,0.3466,1123716,0,2.9054,...,0.00,0,0.00,0,59489.68,1,0,0,55898,Elite
2366,Charge,6,2,92,466,2.1142,0.5226,3012087,0,6.0469,...,1266.97,1,648683.79,1,666319.68,0,1,0,52367,Supp
1812,Charge,0,2,22,490,0.7345,0.3466,578379,1,3.2752,...,400.52,1,125262.91,1,145336.25,1,0,0,51813,Credit
5419,Charge,0,3,136,981,0.7969,0.0000,752685,1,1.7908,...,0.00,0,0.00,0,28149.28,1,0,0,55420,Credit
4774,Charge,1,1,31,981,0.9341,0.1831,174306,1,5.5806,...,0.00,0,0.00,0,271233.04,1,0,0,54775,Supp
2643,Charge,0,2,22,1362,6.6596,0.2986,624358,0,7.0010,...,0.00,0,0.00,0,1151416.24,1,0,0,52644,Elite
3120,Charge,0,3,4,0,0.7969,0.0000,2918974,0,1.8591,...,0.00,0,0.00,0,12110.47,1,0,0,53121,Credit
6177,Charge,0,2,6,844,0.7969,0.0000,2918974,1,4.7619,...,475.21,1,95785.46,1,60999.97,1,0,0,56178,Supp
7083,Charge,0,4,36,381,0.7969,0.1155,57837,0,1.8880,...,2422.39,1,113242.25,1,120579.67,1,0,0,57084,Credit
7843,Charge,5,3,16,1526,2.5778,0.4142,713070,0,5.7166,...,6859.44,1,606050.81,1,573075.39,0,1,0,57844,Supp
9610,Charge,0,0,24,1252,0.7969,0.1831,142614,0,2.1529,...,1254.24,1,108727.90,1,70709.43,1,0,0,59611,Credit
3424,Charge,0,8,92,2441,0.7969,0.1831,142614,1,1.8349,...,0.00,0,0.00,0,153619.01,1,0,0,53425,Credit
5314,Charge,4,2,29,381,0.5568,0.0000,2918974,0,5.2646,...,0.00,0,0.00,0,219290.56,0,0,1,55315,Elite
9812,Charge,0,1,40,566,0.7969,0.2310,420666,0,3.8066,...,8890.68,1,94084.14,1,113342.13,1,0,0,59813,Credit
3230,Charge,3,3,18,1188,1.3400,0.4621,4155881,0,4.5852,...,4042.03,1,496011.79,1,279368.83,0,0,1,53231,Supp
9440,Charge,0,4,7,0,0.2686,0.1155,79230,0,4.2202,...,0.00,0,0.00,0,66314.55,1,0,0,59441,Credit
4332,Charge,0,7,69,853,0.7969,0.0000,2918974,0,1.4000,...,1970.39,1,86821.56,1,89041.33,1,0,0,54333,Credit
2762,Charge,5,1,9,0,0.3267,0.0000,2918974,0,5.3842,...,0.00,0,0.00,0,86604.45,0,1,0,52763,Elite
3698,Charge,3,2,15,439,0.7819,0.1155,237009,1,5.0204,...,16462.34,1,223567.80,1,232794.59,0,0,1,53699,Supp
3104,Charge,8,3,207,3045,7.2029,0.8351,21133561,0,5.4299,...,0.00,0,0.00,0,1543530.41,0,1,0,53105,Supp
285,Charge,0,3,5,310,0.3106,0.1155,205998,0,3.2191,...,0.00,0,0.00,0,91860.55,1,0,0,50286,Elite
2426,Charge,0,2,118,414,0.7969,0.1831,318856,0,3.6540,...,0.00,0,0.00,0,36108.07,1,0,0,52427,Credit
4821,Charge,0,2,74,981,0.7969,0.6381,10092509,1,6.4807,...,0.00,0,0.00,0,884433.91,1,0,0,54822,Credit
8787,Charge,3,6,35,673,1.1807,0.4513,9289030,0,1.3097,...,0.00,0,0.00,0,142008.54,0,0,1,58788,Elite
6380,Charge,5,1,126,525,1.4167,0.0000,2918974,0,5.6584,...,0.00,0,0.00,0,303922.68,0,1,0,56381,Supp
2212,Charge,0,4,7,0,0.7969,0.3662,301074,0,0.2467,...,74.15,1,2299.46,1,2967.28,1,0,0,52213,Credit
1384,Charge,2,4,7,0,0.1288,0.2986,301074,0,2.3924,...,0.00,0,0.00,0,38765.25,0,0,1,51385,Elite
6336,Charge,5,2,15,190,5.0358,0.1831,234737,0,5.2987,...,8563.27,1,1372694.48,1,1500596.08,0,1,0,56337,Supp
9395,Charge,3,2,16,1758,0.7711,0.0000,2918974,0,4.8182,...,499.76,1,143182.49,1,158181.30,0,0,1,59396,Supp
4077,Charge,9,3,296,1849,3.5599,0.8047,15703121,0,6.1781,...,0.00,0,0.00,0,881404.68,0,1,0,54078,Supp

In [274]:
df_v = df[['KEY','pred']]
df_v.to_csv('kowshik_pred16.csv',index=False,index_label=False,header=False)